// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	models "github.com/BolajiOlajide/go-apple-signin/models"
	mock "github.com/stretchr/testify/mock"
)

// AuthorizationTokenService is an autogenerated mock type for the AuthorizationTokenService type
type AuthorizationTokenService struct {
	mock.Mock
}

// GetAuthorizationToken provides a mock function with given fields: code, options, authTokenOption
func (_m *AuthorizationTokenService) GetAuthorizationToken(code string, options models.AuthURLOptions, authTokenOption models.AuthTokenOption) (string, error) {
	ret := _m.Called(code, options, authTokenOption)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, models.AuthURLOptions, models.AuthTokenOption) string); ok {
		r0 = rf(code, options, authTokenOption)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, models.AuthURLOptions, models.AuthTokenOption) error); ok {
		r1 = rf(code, options, authTokenOption)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
